#!/bin/bash
PATH=/bin:/usr/bin

get_file_list() {
    find $* -maxdepth 1 -name "*.lua" ! -executable -print0 | xargs -0 ./get-requires | grep -v -e'^[#!]';
}

format_files() {
    echo '<Ui xmlns="http://www.blizzard.com/wow/ui/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.blizzard.com/wow/ui/ ..\FrameXML\UI.xsd">'
    while read f; do
        f=`basename $f | sed -e 's#/#\\\\#g'`
        echo '    <Script file="'$f'"/>'
    done;
    echo "</Ui>"
}

case $* in 
    wow/files.xml) get_file_list wow | format_files >$* ;;
    files.xml) get_file_list . | format_files >$* ;;
    *) get_file_list `dirname $*` | grep -e "^`dirname $*`" | format_files >"$*" ;;
esac
