#!/bin/bash
PATH=/bin:/usr/bin:$HOME/bin:$FM_ROOT

source fm-library.sh
make_root
cd $root

if [ $# = 0 ]; then
	rm -f .fm/default
	exit
fi

function search_projects {
	find .fm/* -maxdepth 0 -type d | sed 's/.*\///' | grep -i $1
}

c=`search_projects $* | wc -l`
if [ $c = 0 ]; then
	echo "No matches found for pattern: $1" 1>&2
	exit 1
elif [ $c -gt 1 ]; then
	echo "Ambiguous argument: $1" 1>&2
	search_projects $* 1>&2
	exit 1
else
	search_projects $* | tee .fm/default
fi
